paging = false
pager_command = ""
auto_clear = false
english_only = false
theme = "wudao"
http_proxy = ""
clear_screen = false
freq_alert = false
# （开发中）安装了emoji字体的可以输出一些emoji字符，just for fun
enable_emoji = true

[logging]
  enable = true
  path = ""
  level = "info"
  stderr = false
  redirect_to_stream = false
